### ISSUE TITLE
Unknown Target Value

### ISSUE THREAD

**Issue by njdevils9** [trussworks/terraform-aws-ou-scp#14]
I'd first like to say thank you for putting the initial work into this module. It looks like it will be really helpful! I'm running into an issue that I hope is easy to resolve..

The description of the required value for `target`  is a little vague.. Is this module expecting the ARN, ID, a name tag of the desired OU you wish to apply these SCP's to or something else?

Since I already have a handful of OU's deployed to my organization, I want to perform a data lookup on a specific OU for testing. 

```
data "aws_organizations_organization" "my_org" { }

data "aws_organizations_organizational_units" "my_ou" {
   parent_id = data.aws_organizations_organization.my_ord.roots[0].id
}
```

```
module "aws_govcloud_ou_scps" {
  source  = "trussworks/ou-scp/aws"
  version = "1.2.1"

  target = data.aws_organizations_organizational_units.my_ou
  .
  ..
  ...
}
```

**Comment by plbenpeterson** [comment]
Hi njdevils9,

While I'm not the author, I am also interested in making use of this module and I ran into the same trouble you are having because I was targeting a parent ou that contained child ou's. This module is targeting an ou with both a "name" and an "id" that are string values. when you look at the output of a parent ou object, it contains "children" and "id" among other attributes which don't match the desired target object for this module. In order to get around this I did the following for my parent OU:

```
data "aws_organizations_organization" "org" {}

data "aws_organizations_organizational_units" "parent_ou" {
  parent_id = data.aws_organizations_organization.org.roots[0].id
}

module "github_terraform_aws_ou_scp" {
  source = "../terraform-aws-ou-scp"
  for_each = { for ou in data.aws_organizations_organizational_units.parent_ou.children: ou.name => ou}
  target = each.value
}
```
This worked for me by iterating through all the children ous. If you want to target just a single ou, you could do something like this to target the first element listed in children:

```
module "github_terraform_aws_ou_scp" {
  source = "../terraform-aws-ou-scp"
  target = data.aws_organizations_organizational_units.parent_ou.children[0]

  # restrict region-specific operations to us-west-2
  limit_regions = true
  # - restrict region-specific operations to us-west-2
  allowed_regions = ["us-west-2", "us-east-1"]
}
```

**Comment by njdevils9** [comment]
Hey, that worked! Thanks @plbenpeterson 🙂.
